### ISSUE TITLE
relation editor: Set relation attributes not working

### ISSUE THREAD

**Issue by dvirtz** [loujine/musicbrainz-scripts#86]
The above mentioned script doesn't work for me since the new relationship editor was integrated. Clicking the buttons doesn't seem to do anything.

I verified I'm on the latest version (2023.3.6).
Running with 
- Chrome 112.0.5615.138
- Violentmonkey 2.14.0

**Comment by loujine** [comment]
It should be working again now

**Comment by dvirtz** [comment]
It still doesn't work when work relationships have not been submitted yet.
